var authorList =
	[{name:"Abhishek Jain", papers:[], id:1, url:""},
	{name:"Adam Smith", papers:[], id:2, url:""},
	{name:"Adriana L&oacute;pez-Alt", papers:[], id:3, url:""},
	{name:"Alain Tapp", papers:[], id:4, url:""},
	{name:"Alwyn Roshan Pais", papers:[], id:5, url:""},
	{name:"Amit Sahai", papers:[], id:6, url:""},
	{name:"Amos Beimel", papers:[], id:7, url:""},
	{name:"Andrew C. Yao", papers:[], id:8, url:""},
	{name:"Anwitaman Datta", papers:[], id:9, url:""},
	{name:"Ari Juels", papers:[], id:10, url:""},
	{name:"Avi Wigderson", papers:[], id:11, url:""},
	{name:"Bartosz Przydatek", papers:[], id:12, url:""},
	{name:"Beerendra Kumar", papers:[], id:13, url:""},
	{name:"Benny Pinkas", papers:[], id:14, url:""},
	{name:"Bhiksha Raj", papers:[], id:15, url:""},
	{name:"Boaz Barak", papers:[], id:16, url:""},
	{name:"Christian Cachin", papers:[], id:17, url:""},
	{name:"Claude Cr&eacute;peau", papers:[], id:18, url:""},
	{name:"Claudio Orlandi", papers:[], id:19, url:""},
	{name:"Dan Kenigsberg", papers:[], id:20, url:""},
	{name:"Dan Lund Christensen", papers:[], id:21, url:""},
	{name:"Daniel E. Browne", papers:[], id:22, url:""},
	{name:"Daniel Gottesman", papers:[], id:23, url:""},
	{name:"Daniel Wichs", papers:[], id:24, url:""},
	{name:"Danny Bickson", papers:[], id:25, url:""},
	{name:"Danny Dolev", papers:[], id:26, url:""},
	{name:"David Chaum", papers:[], id:27, url:""},
	{name:"Deepesh Data", papers:[], id:28, url:""},
	{name:"Dinh Tien Tuan Anh", papers:[], id:29, url:""},
	{name:"Dominique Unruh", papers:[], id:30, url:""},
	{name:"Durgesh Kumar Mishra", papers:[], id:31, url:""},
	{name:"Elette Boyle", papers:[], id:32, url:""},
	{name:"Enrique Larraia", papers:[], id:33, url:""},
	{name:"Eran Omri", papers:[], id:34, url:""},
	{name:"Eran Tromer", papers:[], id:35, url:""},
	{name:"Genia Bezman", papers:[], id:36, url:""},
	{name:"Gilad Asharov", papers:[], id:37, url:""},
	{name:"Ilan Orlov", papers:[], id:38, url:""},
	{name:"Ivan Damg&aring;rd", papers:[], id:39, url:""},
	{name:"Jakob Pagter", papers:[], id:40, url:""},
	{name:"Jan Camenisch", papers:[], id:41, url:""},
	{name:"Janus Dam Nielsen", papers:[], id:42, url:""},
	{name:"Jeroen van de Graaf", papers:[], id:43, url:""},
	{name:"Jesper B. Nielsen", papers:[], id:44, url:""},
	{name:"Joan Feigenbaum", papers:[], id:45, url:""},
	{name:"Juan A. Garay", papers:[], id:46, url:""},
	{name:"Ke Yang", papers:[], id:47, url:""},
	{name:"Klearchos Loukopoulos", papers:[], id:48, url:""},
	{name:"Kobbi Nissim", papers:[], id:49, url:""},
	{name:"Kurt Nielsen", papers:[], id:50, url:""},
	{name:"Magendra Pratap Singh", papers:[], id:51, url:""},
	{name:"Manas A. Pathak", papers:[], id:52, url:""},
	{name:"Manoj M. Prabhakaran", papers:[], id:53, url:""},
	{name:"Marcel Keller", papers:[], id:54, url:""},
	{name:"Marcin Wie&sacute;niak", papers:[], id:55, url:""},
	{name:"Marek &#379;ukowski", papers:[], id:56, url:""},
	{name:"Mariana Raykova", papers:[], id:57, url:""},
	{name:"Markus Jakobson", papers:[], id:58, url:""},
	{name:"Martin Geisler", papers:[], id:59, url:""},
	{name:"Martin Hirt", papers:[], id:60, url:""},
	{name:"Martin J. Strauss", papers:[], id:61, url:""},
	{name:"Matthew Franklin", papers:[], id:62, url:""},
	{name:"Matthias Fitzi", papers:[], id:63, url:""},
	{name:"Michael Ben-Or", papers:[], id:64, url:""},
	{name:"Michael O. Rabin", papers:[], id:65, url:""},
	{name:"Michael Schwartzbach", papers:[], id:66, url:""},
	{name:"Michael Zohner", papers:[], id:67, url:""},
	{name:"Mikhail J. Atallah", papers:[], id:68, url:""},
	{name:"Mikkel Kr&oslash;igaard", papers:[], id:69, url:""},
	{name:"Moni Naor", papers:[], id:70, url:""},
	{name:"Neha Koria", papers:[], id:71, url:""},
	{name:"Nigel P. Smart", papers:[], id:72, url:""},
	{name:"Nikhil Kapoor", papers:[], id:73, url:""},
	{name:"Oded Goldreich", papers:[], id:74, url:""},
	{name:"Peter Bogetoft", papers:[], id:75, url:""},
	{name:"Peter Scholl", papers:[], id:76, url:""},
	{name:"Philip MacKenzie", papers:[], id:77, url:""},
	{name:"Quach Vinh Thanh", papers:[], id:78, url:""},
	{name:"Rafail Ostrovsky", papers:[], id:79, url:""},
	{name:"Ramij Rahaman", papers:[], id:80, url:""},
	{name:"Ran Canetti", papers:[], id:81, url:""},
	{name:"Rashid Sheikh", papers:[], id:82, url:""},
	{name:"Ravish Bahety", papers:[], id:83, url:""},
	{name:"Rebecca N. Wright", papers:[], id:84, url:""},
	{name:"Roger Colbeck", papers:[], id:85, url:""},
	{name:"Ronald Cramer", papers:[], id:86, url:""},
	{name:"Rosario Gennaro", papers:[], id:87, url:""},
	{name:"Samiksha Shukla", papers:[], id:88, url:""},
	{name:"Sanjam Garg", papers:[], id:89, url:""},
	{name:"Shafi Goldwasser", papers:[], id:90, url:""},
	{name:"Shailesh Vaya", papers:[], id:91, url:""},
	{name:"Silvio Micali", papers:[], id:92, url:""},
	{name:"Stefan Dziembowski", papers:[], id:93, url:""},
	{name:"Stuart Haver", papers:[], id:94, url:""},
	{name:"T.R. Srinath", papers:[], id:95, url:""},
	{name:"Tal Geula Malkin", papers:[], id:96, url:""},
	{name:"Tal Malkin", papers:[], id:97, url:""},
	{name:"Tal Mor", papers:[], id:98, url:""},
	{name:"Tal Rabin", papers:[], id:99, url:""},
	{name:"Tamir Tassa", papers:[], id:100, url:""},
	{name:"Thomas Jakobsen", papers:[], id:101, url:""},
	{name:"Thomas Schneider", papers:[], id:102, url:""},
	{name:"Tomas Toft", papers:[], id:103, url:""},
	{name:"Tony Thomas", papers:[], id:104, url:""},
	{name:"Tzachy Reinman", papers:[], id:105, url:""},
	{name:"Ueli Maurer", papers:[], id:106, url:""},
	{name:"Uri Feige", papers:[], id:107, url:""},
	{name:"Valerio Pastro", papers:[], id:108, url:""},
	{name:"Vinod M. Prabhakaran", papers:[], id:109, url:""},
	{name:"Vinod Vaikuntanathan", papers:[], id:110, url:""},
	{name:"Wenliang Du", papers:[], id:111, url:""},
	{name:"Yael Tauman Kalai", papers:[], id:112, url:""},
	{name:"Yehuda Lindell", papers:[], id:113, url:""},
	{name:"Yevgeniy Dodis", papers:[], id:114, url:""},
	{name:"Yuval Ishai", papers:[], id:115, url:""}];