var authorList =
	{"Abhishek Jain":"",
	"Adam Smith":"",
	"Adriana L&oacute;pez-Alt":"",
	"Alain Tapp":"",
	"Alwyn Roshan Pais":"",
	"Amit Sahai":"",
	"Amos Beimel":"",
	"Andrew C. Yao":"http://iiis.tsinghua.edu.cn/yao/",
	"Anwitaman Datta":"",
	"Ari Juels":"",
	"Avi Wigderson":"http://www.math.ias.edu/avi/home",
	"Bartosz Przydatek":"",
	"Beerendra Kumar":"",
	"Benny Pinkas":"",
	"Bhiksha Raj":"",
	"Boaz Barak":"",
	"Christian Cachin":"",
	"Claude Cr&eacute;peau":"",
	"Claudio Orlandi":"",
	"Dan Kenigsberg":"",
	"Dan Lund Christensen":"",
	"Daniel E. Browne":"",
	"Daniel Gottesman":"",
	"Daniel Wichs":"",
	"Danny Bickson":"",
	"Danny Dolev":"",
	"David Chaum":"",
	"Deepesh Data":"",
	"Dinh Tien Tuan Anh":"",
	"Dominique Unruh":"",
	"Durgesh Kumar Mishra":"",
	"Elette Boyle":"",
	"Enrique Larraia":"",
	"Eran Omri":"",
	"Eran Tromer":"",
	"Genia Bezman":"",
	"Gilad Asharov":"",
	"Ilan Orlov":"",
	"Ivan Damg&aring;rd":"",
	"Jakob Pagter":"",
	"Jan Camenisch":"",
	"Janus Dam Nielsen":"",
	"Jeroen van de Graaf":"",
	"Jesper B. Nielsen":"",
	"Joan Feigenbaum":"",
	"Juan A. Garay":"",
	"Ke Yang":"",
	"Klearchos Loukopoulos":"",
	"Kobbi Nissim":"",
	"Kurt Nielsen":"",
	"Magendra Pratap Singh":"",
	"Manas A. Pathak":"",
	"Manoj M. Prabhakaran":"",
	"Marcel Keller":"",
	"Marcin Wie&sacute;niak":"",
	"Marek &#379;ukowski":"",
	"Mariana Raykova":"",
	"Markus Jakobson":"",
	"Martin Geisler":"",
	"Martin Hirt":"",
	"Martin J. Strauss":"",
	"Matthew Franklin":"",
	"Matthias Fitzi":"",
	"Michael Ben-Or":"",
	"Michael O. Rabin":"",
	"Michael Schwartzbach":"",
	"Michael Zohner":"",
	"Mikhail J. Atallah":"",
	"Mikkel Kr&oslash;igaard":"",
	"Moni Naor":"",
	"Neha Koria":"",
	"Nigel P. Smart":"",
	"Nikhil Kapoor":"",
	"Oded Goldreich":"http://www.wisdom.weizmann.ac.il/~oded/",
	"Peter Bogetoft":"",
	"Peter Scholl":"",
	"Philip MacKenzie":"",
	"Quach Vinh Thanh":"",
	"Rafail Ostrovsky":"",
	"Ramij Rahaman":"",
	"Ran Canetti":"",
	"Rashid Sheikh":"",
	"Ravish Bahety":"",
	"Rebecca N. Wright":"",
	"Roger Colbeck":"",
	"Ronald Cramer":"",
	"Rosario Gennaro":"",
	"Samiksha Shukla":"",
	"Sanjam Garg":"",
	"Shafi Goldwasser":"",
	"Shailesh Vaya":"",
	"Silvio Micali":"http://people.csail.mit.edu/silvio/",
	"Stefan Dziembowski":"",
	"Stuart Haver":"",
	"T.R. Srinath":"",
	"Tal Geula Malkin":"",
	"Tal Malkin":"",
	"Tal Mor":"",
	"Tal Rabin":"",
	"Tamir Tassa":"",
	"Thomas Jakobsen":"",
	"Thomas Schneider":"",
	"Tomas Toft":"",
	"Tony Thomas":"",
	"Tzachy Reinman":"",
	"Ueli Maurer":"",
	"Uri Feige":"",
	"Valerio Pastro":"",
	"Vinod M. Prabhakaran":"",
	"Vinod Vaikuntanathan":"",
	"Wenliang Du":"",
	"Yael Tauman Kalai":"",
	"Yehuda Lindell":"",
	"Yevgeniy Dodis":"",
	"Yuval Ishai":""};